x1 = int(input("x1 = "))
y1 = int(input("y1 = "))
x2 = int(input("x2 = "))
y2 = int(input("y2 = "))
d = pow(((x2-x1)*(x2-x1) + (y2-y1)*(y2-y1)),0.5)
print("Distance between: (",x1,",",y1,") and (",x2,",",y2,") =",d,"units.")
